version: "3"
services:
    web:
        image: cool-store-web
        ports:
            - "5000:5000"
        depends_on:
            - db
    db:
        image: cool-store-db
        environment:
            SA_PASSWORD: "_SqLr0ck5_"
            ACCEPT_EULA: "Y"
        ports:
            - "1500:1433"